fix(quark): replace version by a string in quark definition
Hi, I'm experiencing an issue after installing AlgaLib in Quarks:

  ERROR: Syntax error, unexpected INTEGER, expecting NAME or WHILE or '[' or '('
    in interpreted text
    line 7 char 16:

    version:    1.1.1,
                 ^

During last update, you bumped the version from 1.1 to 1.1.1.
Without quotes I guess it was working because Quarks was probably using the
value as a float. Now it can only be a string a string, it should be protected.

Signed-off-by: Youenn Piolet <piolet.y@gmail.com>